In [2]:
import numpy as np

# Part 1: Creating and Reshaping Arrays

In [3]:
# 1. Create Arrays:
arr1 = np.linspace(0,50,10)
print(arr1)
arr2 = np.random.randint(5,20,9)
arr2=arr2.reshape(3,3)
print(arr2)
# 2. Array Dimensions:
print("dimension of arr1: ",arr1.ndim)
print("dimension of arr2: ",arr2.ndim)
print("shape of arr1: ",arr1.shape)
print("shape of arr2: ",arr2.shape)
# 3. Reshaping:
arr1=arr1.reshape(2,5)
print(arr1)
arr1=arr1.reshape(-1)
print(arr1)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]
[[14  6 16]
 [11 12  7]
 [ 6  7 14]]
dimension of arr1:  1
dimension of arr2:  2
shape of arr1:  (10,)
shape of arr2:  (3, 3)
[[ 0.          5.55555556 11.11111111 16.66666667 22.22222222]
 [27.77777778 33.33333333 38.88888889 44.44444444 50.        ]]
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


# Part 2: Indexing and Slicing

In [4]:
# 4. Indexing:
print(arr2[1,2])
print(arr2[:2,1:])
# 5. Slicing:
print(arr1[:4])
print(arr1[::-1])

7
[[ 6 16]
 [12  7]]
[ 0.          5.55555556 11.11111111 16.66666667]
[50.         44.44444444 38.88888889 33.33333333 27.77777778 22.22222222
 16.66666667 11.11111111  5.55555556  0.        ]


#Part 3: Array Operations

In [5]:
# 6. Array Arithmetic:
arr3 = np.arange(1,11)
print(arr3)
print(arr1+arr3)
print(arr1*arr3)
print(arr3-5)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.          7.55555556 14.11111111 20.66666667 27.22222222 33.77777778
 40.33333333 46.88888889 53.44444444 60.        ]
[  0.          11.11111111  33.33333333  66.66666667 111.11111111
 166.66666667 233.33333333 311.11111111 400.         500.        ]
[-4 -3 -2 -1  0  1  2  3  4  5]


# Part 4: Random Number Generation and Copying  

In [6]:
# 7. Random Numbers:
arr4=np.random.rand(5)
print(arr4)
arr5=np.random.randint(-1,1,5)
print(arr5)

[0.2114983  0.91195376 0.68413827 0.07409246 0.94392496]
[ 0  0 -1  0 -1]


# Part 5: Bonus

In [7]:
# 8. Challenge Task:
n=int(input("enter value: "))
arr6=np.random.randint(1,100,n*n)
arr6=arr6.reshape(n,n)
print(arr6)
print(np.sum(arr6))

enter value: 5
[[35 58 25 51 17]
 [ 7 62 95 89  9]
 [19  9 99 82 72]
 [89 80 11 42 28]
 [46 22 34 16 68]]
1165
